<?php

namespace Database\Seeders;

use App\Models\Bien;
use App\Models\Option;
use App\Models\Statut;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class BienSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Récupérer tous les utilisateurs disponibles
        $users = User::all();

        // Si aucun utilisateur n'existe, créer un utilisateur par défaut
        if ($users->isEmpty()) {
            $users = collect([
                User::create([
                    'prenom' => 'Default',
                    'nom' => 'User',
                    'tel' => '0197000000',
                    'email' => 'default@loggyimmo.bj',
                    'password' => Hash::make('password'),
                    'type' => 'user',
                ])
            ]);
        }

        // Annonces reflétant le marché immobilier béninois (Cotonou,
        // Abomey-Calavi, Porto-Novo, Sèmè-Podji et les grandes villes de
        // l'intérieur). Quelques repères sur le vocabulaire utilisé :
        // - "Chambre salon" : une pièce à vivre + une chambre, le type de
        //   logement locatif le plus répandu à Cotonou.
        // - "Sanitaire" : douche/WC intégrés au logement (par opposition à
        //   une cour avec sanitaire commun).
        // - "X chambres salon" : X chambres + un salon, formulation standard
        //   des annonces béninoises (plutôt que "TX" à la française).
        // - "Cour clôturée" : atout de sécurité très recherché.
        // - Pas de code postal : ce système n'est pas utilisé au quotidien
        //   pour les adresses résidentielles au Bénin — les annonces
        //   s'orientent par quartier et repère (église, carrefour, école...).
        $biens = [
            [
                'titre' => 'Chambre salon sanitaire disponible à Womey',
                'surface' => 35.00,
                'description' => 'Chambre salon avec sanitaire interne à louer à Womey, dans une cour clôturée et calme. Eau SONEB et électricité SBEE disponibles. Idéal pour une petite famille ou un(e) célibataire. Avance de 6 mois exigée.',
                'pieces' => 2,
                'chambres' => 1,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Womey, non loin du CEG Womey',
                'ville' => 'Abomey-Calavi',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 30000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [5, 9], // Cour clôturée, Forage
            ],
            [
                'titre' => 'Chambre salon à louer à Zogbo',
                'surface' => 28.00,
                'description' => 'Chambre salon simple à louer à Zogbo, cour commune clôturée avec voisinage calme. Proche des commerces et du goudron.',
                'pieces' => 2,
                'chambres' => 1,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Zogbo, quartier Zogbo Est',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 25000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [5],
            ],
            [
                'titre' => '2 chambres salon à louer à Fidjrossè',
                'surface' => 55.00,
                'description' => '2 chambres salon avec sanitaire interne à louer à Fidjrossè, non loin de la voie pavée. Cour clôturée, parking pour véhicule, climatisation dans une chambre.',
                'pieces' => 3,
                'chambres' => 2,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Fidjrossè, non loin du carrefour Sèkandji',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 85000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [2, 5, 7],
            ],
            [
                'titre' => '3 chambres salon à louer à Cadjèhoun',
                'surface' => 75.00,
                'description' => 'Belle villa 3 chambres salon à louer à Cadjèhoun, quartier résidentiel et sécurisé. Cour clôturée avec portail, groupe électrogène, forage.',
                'pieces' => 4,
                'chambres' => 3,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Cadjèhoun, non loin de l\'aéroport',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 150000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [2, 5, 7, 8, 9],
            ],
            [
                'titre' => 'Villa duplex à vendre à Sainte Rita',
                'surface' => 220.00,
                'description' => 'Villa duplex de standing à vendre à Sainte Rita, 4 chambres salon, 2 salons, cour clôturée avec portail automatique. Forage, groupe électrogène, titre foncier disponible.',
                'pieces' => 6,
                'chambres' => 4,
                'salons' => 2,
                'etage' => 1,
                'adresse' => 'Sainte Rita, derrière l\'église Sainte Rita',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'villa',
                'statut' => 'disponible',
                'prix' => 85000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 4, 5, 7, 8, 9, 10],
            ],
            [
                'titre' => 'Villa basse à vendre à Akpakpa',
                'surface' => 150.00,
                'description' => 'Villa basse (plain-pied) de 3 chambres salon à vendre à Akpakpa, sur terrain clôturé de 400 m². Idéale pour une famille, quartier calme non loin du pont Akpakpa.',
                'pieces' => 4,
                'chambres' => 3,
                'salons' => 1,
                'etage' => null,
                'adresse' => 'Akpakpa, non loin du pont Akpakpa',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'villa',
                'statut' => 'disponible',
                'prix' => 42000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 5, 9],
            ],
            [
                'titre' => 'Studio meublé à louer à Cocotomey',
                'surface' => 22.00,
                'description' => 'Studio meublé prêt à vivre à louer à Cocotomey, sur l\'axe Calavi. Climatisation, eau et électricité comprises, idéal étudiant ou jeune professionnel.',
                'pieces' => 1,
                'chambres' => 0,
                'salons' => 0,
                'etage' => 0,
                'adresse' => 'Cocotomey, sur l\'axe Calavi',
                'ville' => 'Abomey-Calavi',
                'codePostal' => null,
                'categorie' => 'studio',
                'statut' => 'disponible',
                'prix' => 45000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [7, 9],
            ],
            [
                'titre' => 'Appartement 2 chambres salon meublé à louer à Ganhi',
                'surface' => 60.00,
                'description' => 'Appartement meublé 2 chambres salon à louer à Ganhi, en plein centre de Cotonou. Climatisation dans toutes les pièces, ascenseur, gardien.',
                'pieces' => 3,
                'chambres' => 2,
                'salons' => 1,
                'etage' => 2,
                'adresse' => 'Ganhi, Cotonou centre',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 220000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [6, 7, 10],
            ],
            [
                'titre' => 'Maison à étage à vendre à Godomey',
                'surface' => 180.00,
                'description' => 'Maison à étage à vendre à Godomey, 4 chambres salon réparties sur 2 niveaux, cour clôturée, forage et groupe électrogène. Proche du marché Womey.',
                'pieces' => 6,
                'chambres' => 4,
                'salons' => 2,
                'etage' => 1,
                'adresse' => 'Godomey, carrefour Godomey',
                'ville' => 'Abomey-Calavi',
                'codePostal' => null,
                'categorie' => 'maison',
                'statut' => 'disponible',
                'prix' => 38000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 5, 8, 9],
            ],
            [
                'titre' => 'Terrain nu titré à vendre à Togba',
                'surface' => 600.00,
                'description' => 'Terrain nu de 600 m² à vendre à Togba, zone lotie, à 5 minutes du goudron. Titre foncier (ACD) disponible, idéal pour construction résidentielle.',
                'pieces' => null,
                'chambres' => null,
                // Contrairement à pieces/chambres, la colonne `salons` est
                // NOT NULL (défaut 0) en base — cf. migration
                // add_salons_to_biens_table.
                'salons' => 0,
                'etage' => null,
                'adresse' => 'Togba, zone loties',
                'ville' => 'Abomey-Calavi',
                'codePostal' => null,
                'statut' => 'disponible',
                'prix' => 12000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [],
            ],
            [
                'titre' => 'Villa duplex de haut standing à vendre à Fidjrossè',
                'surface' => 300.00,
                'description' => 'Exceptionnelle villa duplex de haut standing à vendre à Fidjrossè. 5 chambres salon, piscine, cour clôturée avec portail automatique, forage, groupe électrogène.',
                'pieces' => 7,
                'chambres' => 5,
                'salons' => 2,
                'etage' => 1,
                'adresse' => 'Fidjrossè, non loin de la Radisson Blu',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'villa',
                'statut' => 'disponible',
                'prix' => 145000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 4, 5, 7, 8, 9, 10],
            ],
            [
                'titre' => 'Chambre salon sanitaire à louer à Missité',
                'surface' => 32.00,
                'description' => 'Chambre salon avec sanitaire interne à louer à Missité, quartier résidentiel calme. Cour clôturée, parking disponible.',
                'pieces' => 2,
                'chambres' => 1,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Missité, zone résidentielle',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 35000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [2, 5],
            ],
            [
                'titre' => '3 chambres salon à vendre à Ouando',
                'surface' => 130.00,
                'description' => 'Maison 3 chambres salon à vendre à Ouando, Porto-Novo. Cour clôturée, forage, quartier calme non loin du marché Ouando.',
                'pieces' => 4,
                'chambres' => 3,
                'salons' => 1,
                'etage' => null,
                'adresse' => 'Ouando, non loin du marché Ouando',
                'ville' => 'Porto-Novo',
                'codePostal' => null,
                'categorie' => 'maison',
                'statut' => 'disponible',
                'prix' => 28000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [5, 9],
            ],
            [
                'titre' => 'Appartement meublé à louer à Gbégamey',
                'surface' => 65.00,
                'description' => 'Appartement meublé 2 chambres salon à louer à Gbégamey, proche du lycée. Climatisation, ascenseur, gardien 24h/24.',
                'pieces' => 3,
                'chambres' => 2,
                'salons' => 1,
                'etage' => 3,
                'adresse' => 'Gbégamey, non loin du lycée Gbégamey',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 200000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [6, 7, 10],
            ],
            [
                'titre' => 'Maison à étage à louer à Vêdoko',
                'surface' => 140.00,
                'description' => 'Maison à étage 4 chambres salon à louer à Vêdoko, cour clôturée, forage, groupe électrogène. Quartier calme et sécurisé.',
                'pieces' => 5,
                'chambres' => 4,
                'salons' => 1,
                'etage' => 1,
                'adresse' => 'Vêdoko, quartier Vêdoko',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'maison',
                'statut' => 'disponible',
                'prix' => 250000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [2, 5, 8, 9],
            ],
            [
                'titre' => 'Villa avec piscine à vendre à Fidjrossè',
                'surface' => 260.00,
                'description' => 'Villa 4 chambres salon avec piscine privée à vendre à Fidjrossè. Cour clôturée, jardin paysager, forage, groupe électrogène.',
                'pieces' => 6,
                'chambres' => 4,
                'salons' => 2,
                'etage' => null,
                'adresse' => 'Fidjrossè, zone résidentielle',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'villa',
                'statut' => 'disponible',
                'prix' => 98000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 5, 8, 9],
            ],
            [
                'titre' => 'Chambre salon à louer à Agla',
                'surface' => 26.00,
                'description' => 'Chambre salon simple à louer à Agla, cour commune clôturée. Proche des transports en commun (zémidjans, taxis).',
                'pieces' => 2,
                'chambres' => 1,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Agla, zone Agla-Est',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 22000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [5],
            ],
            [
                'titre' => '2 chambres salon sanitaire à louer à Womey',
                'surface' => 50.00,
                'description' => '2 chambres salon avec sanitaire interne à louer à Womey, cour clôturée, forage, parking disponible. Non loin de l\'université d\'Abomey-Calavi.',
                'pieces' => 3,
                'chambres' => 2,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Womey, non loin de l\'UAC',
                'ville' => 'Abomey-Calavi',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 65000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [2, 5, 9],
            ],
            [
                'titre' => 'Studio à louer à Jonquet',
                'surface' => 20.00,
                'description' => 'Studio simple à louer à Jonquet, quartier animé proche des commerces et de la plage. Sanitaire interne, eau et électricité disponibles.',
                'pieces' => 1,
                'chambres' => 0,
                'salons' => 0,
                'etage' => 1,
                'adresse' => 'Jonquet, quartier Jonquet',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'studio',
                'statut' => 'disponible',
                'prix' => 38000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [9],
            ],
            [
                'titre' => 'Immeuble R+2 à vendre à Akpakpa',
                'surface' => 450.00,
                'description' => 'Immeuble de rapport R+2 à vendre à Akpakpa, 6 appartements 2 chambres salon, parking commun, groupe électrogène et gardien. Excellent rendement locatif.',
                'pieces' => 12,
                'chambres' => 6,
                'salons' => 3,
                'etage' => 2,
                'adresse' => 'Akpakpa, non loin du marché Akpakpa',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'maison',
                'statut' => 'disponible',
                'prix' => 180000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 6, 8, 10],
            ],
            [
                'titre' => 'Terrain loti à vendre à Ekpè',
                'surface' => 400.00,
                'description' => 'Terrain loti de 400 m² à vendre à Ekpè, Sèmè-Podji. Zone en plein essor, proche de la frontière et de l\'aéroport. Document ACD disponible.',
                'pieces' => null,
                'chambres' => null,
                // Contrairement à pieces/chambres, la colonne `salons` est
                // NOT NULL (défaut 0) en base — cf. migration
                // add_salons_to_biens_table.
                'salons' => 0,
                'etage' => null,
                'adresse' => 'Ekpè, zone lotie',
                'ville' => 'Sèmè-Podji',
                'codePostal' => null,
                'statut' => 'disponible',
                'prix' => 8000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [],
            ],
            [
                'titre' => 'Villa duplex à louer à Ouidah',
                'surface' => 190.00,
                'description' => 'Villa duplex 4 chambres salon à louer à Ouidah, cour clôturée avec jardin, forage. Quartier calme non loin de la basilique.',
                'pieces' => 5,
                'chambres' => 4,
                'salons' => 1,
                'etage' => 1,
                'adresse' => 'Ouidah centre, non loin de la basilique',
                'ville' => 'Ouidah',
                'codePostal' => null,
                'categorie' => 'villa',
                'statut' => 'disponible',
                'prix' => 180000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [3, 5, 9],
            ],
            [
                'titre' => 'Maison basse à vendre à Abomey',
                'surface' => 160.00,
                'description' => 'Maison basse 4 chambres salon à vendre à Abomey, terrain clôturé de 500 m². Quartier historique, proche des palais royaux.',
                'pieces' => 5,
                'chambres' => 4,
                'salons' => 1,
                'etage' => null,
                'adresse' => 'Abomey centre, non loin des palais royaux',
                'ville' => 'Abomey',
                'codePostal' => null,
                'categorie' => 'maison',
                'statut' => 'disponible',
                'prix' => 22000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [5, 9],
            ],
            [
                'titre' => '3 chambres salon à louer à Bohicon',
                'surface' => 90.00,
                'description' => '3 chambres salon à louer à Bohicon, carrefour ferroviaire du Zou. Cour clôturée, forage, quartier calme.',
                'pieces' => 4,
                'chambres' => 3,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Bohicon centre, non loin de la gare',
                'ville' => 'Bohicon',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 65000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [5, 9],
            ],
            [
                'titre' => 'Chambre salon sanitaire à louer à Parakou',
                'surface' => 30.00,
                'description' => 'Chambre salon avec sanitaire interne à louer à Parakou, quartier Banikanni. Cour clôturée, calme et sécurisé.',
                'pieces' => 2,
                'chambres' => 1,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Banikanni, Parakou',
                'ville' => 'Parakou',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 28000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [5],
            ],
            [
                'titre' => 'Villa avec cour clôturée à vendre à Natitingou',
                'surface' => 175.00,
                'description' => 'Villa 4 chambres salon à vendre à Natitingou, terrain clôturé de 600 m² avec jardin. Vue sur les montagnes de l\'Atacora.',
                'pieces' => 5,
                'chambres' => 4,
                'salons' => 1,
                'etage' => null,
                'adresse' => 'Natitingou centre',
                'ville' => 'Natitingou',
                'codePostal' => null,
                'categorie' => 'villa',
                'statut' => 'disponible',
                'prix' => 32000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [3, 5, 9],
            ],
            [
                'titre' => '2 chambres salon à vendre à Djougou',
                'surface' => 65.00,
                'description' => 'Maison 2 chambres salon à vendre à Djougou, quartier calme. Cour clôturée, forage, proche du grand marché.',
                'pieces' => 3,
                'chambres' => 2,
                'salons' => 1,
                'etage' => null,
                'adresse' => 'Djougou centre, non loin du grand marché',
                'ville' => 'Djougou',
                'codePostal' => null,
                'categorie' => 'maison',
                'statut' => 'disponible',
                'prix' => 15000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [5, 9],
            ],
            [
                'titre' => 'Appartement meublé à louer à Cadjèhoun',
                'surface' => 58.00,
                'description' => 'Appartement meublé 2 chambres salon à louer à Cadjèhoun, immeuble sécurisé avec ascenseur et gardien. Climatisation dans toutes les pièces.',
                'pieces' => 3,
                'chambres' => 2,
                'salons' => 1,
                'etage' => 2,
                'adresse' => 'Cadjèhoun, à 300m de l\'aéroport',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 240000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [6, 7, 10],
            ],
            [
                'titre' => 'Chambre salon disponible à Womey',
                'surface' => 30.00,
                'description' => 'Chambre salon disponible immédiatement à Womey, cour clôturée et calme. Proche du marché Womey et des transports.',
                'pieces' => 2,
                'chambres' => 1,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Womey, non loin du marché Womey',
                'ville' => 'Abomey-Calavi',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 27000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [5],
            ],
            [
                'titre' => 'Studio meublé à louer à Sainte Rita',
                'surface' => 24.00,
                'description' => 'Studio meublé climatisé à louer à Sainte Rita, quartier résidentiel calme. Sanitaire interne, forage.',
                'pieces' => 1,
                'chambres' => 0,
                'salons' => 0,
                'etage' => 0,
                'adresse' => 'Sainte Rita, quartier résidentiel',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'studio',
                'statut' => 'disponible',
                'prix' => 55000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [7, 9],
            ],
            [
                'titre' => 'Villa duplex à vendre à Godomey',
                'surface' => 210.00,
                'description' => 'Villa duplex 4 chambres salon à vendre à Godomey, cour clôturée avec portail, forage, groupe électrogène. Proche du carrefour Godomey.',
                'pieces' => 6,
                'chambres' => 4,
                'salons' => 2,
                'etage' => 1,
                'adresse' => 'Godomey, carrefour Godomey',
                'ville' => 'Abomey-Calavi',
                'codePostal' => null,
                'categorie' => 'villa',
                'statut' => 'reserve',
                'prix' => 62000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 5, 8, 9],
            ],
            [
                'titre' => '3 chambres salon sanitaire à louer à Fidjrossè',
                'surface' => 80.00,
                'description' => '3 chambres salon avec sanitaire interne à louer à Fidjrossè, cour clôturée, parking, climatisation. Quartier très prisé de Cotonou.',
                'pieces' => 4,
                'chambres' => 3,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Fidjrossè, zone résidentielle',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'loue',
                'prix' => 165000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [2, 5, 7],
            ],
            [
                'titre' => 'Maison à étage à vendre à Lokossa',
                'surface' => 150.00,
                'description' => 'Maison à étage 4 chambres salon à vendre à Lokossa, chef-lieu du Mono. Cour clôturée, forage, quartier calme.',
                'pieces' => 5,
                'chambres' => 4,
                'salons' => 1,
                'etage' => 1,
                'adresse' => 'Lokossa centre',
                'ville' => 'Lokossa',
                'codePostal' => null,
                'categorie' => 'maison',
                'statut' => 'disponible',
                'prix' => 20000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [5, 9],
            ],
            [
                'titre' => 'Villa de standing à vendre à Cadjèhoun',
                'surface' => 280.00,
                'description' => 'Villa de standing 5 chambres salon à vendre à Cadjèhoun, piscine, cour clôturée avec portail automatique, forage, groupe électrogène. Quartier huppé proche de l\'aéroport.',
                'pieces' => 7,
                'chambres' => 5,
                'salons' => 2,
                'etage' => null,
                'adresse' => 'Cadjèhoun, quartier résidentiel',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'villa',
                'statut' => 'vendu',
                'prix' => 160000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 4, 5, 8, 9, 10],
            ],
            [
                'titre' => 'Chambre salon à louer à Tori-Bossito',
                'surface' => 27.00,
                'description' => 'Chambre salon simple à louer à Tori-Bossito, quartier calme et accessible. Cour commune clôturée.',
                'pieces' => 2,
                'chambres' => 1,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Tori-Bossito centre',
                'ville' => 'Tori-Bossito',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 18000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [5],
            ],
            [
                'titre' => '2 chambres salon à louer à Pahou',
                'surface' => 48.00,
                'description' => '2 chambres salon à louer à Pahou, sur l\'axe Ouidah-Cotonou. Cour clôturée, forage, proche du goudron.',
                'pieces' => 3,
                'chambres' => 2,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Pahou, sur l\'axe Ouidah-Cotonou',
                'ville' => 'Ouidah',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 55000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [5, 9],
            ],
            [
                'titre' => 'Terrain nu à vendre à Allada',
                'surface' => 500.00,
                'description' => 'Terrain nu de 500 m² à vendre à Allada, zone en développement. Idéal pour construction résidentielle ou investissement. Document ACD disponible.',
                'pieces' => null,
                'chambres' => null,
                // Contrairement à pieces/chambres, la colonne `salons` est
                // NOT NULL (défaut 0) en base — cf. migration
                // add_salons_to_biens_table.
                'salons' => 0,
                'etage' => null,
                'adresse' => 'Allada, zone lotie',
                'ville' => 'Allada',
                'codePostal' => null,
                'statut' => 'disponible',
                'prix' => 5000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [],
            ],
            [
                'titre' => 'Villa avec piscine à louer à Fidjrossè',
                'surface' => 240.00,
                'description' => 'Villa 4 chambres salon avec piscine à louer à Fidjrossè, cour clôturée, jardin, forage, groupe électrogène. Idéal pour expatriés.',
                'pieces' => 6,
                'chambres' => 4,
                'salons' => 2,
                'etage' => null,
                'adresse' => 'Fidjrossè, zone résidentielle',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'villa',
                'statut' => 'disponible',
                'prix' => 650000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 5, 8, 9],
            ],
            [
                'titre' => 'Appartement 3 chambres salon à vendre à Porto-Novo',
                'surface' => 100.00,
                'description' => 'Appartement 3 chambres salon à vendre à Attakè, Porto-Novo. Cour clôturée, forage, proche du palais présidentiel.',
                'pieces' => 4,
                'chambres' => 3,
                'salons' => 1,
                'etage' => 1,
                'adresse' => 'Attakè, non loin du palais présidentiel',
                'ville' => 'Porto-Novo',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 32000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [5, 9],
            ],
            [
                'titre' => 'Chambre salon sanitaire à louer à Godomey',
                'surface' => 33.00,
                'description' => 'Chambre salon avec sanitaire interne à louer à Godomey, cour clôturée et sécurisée, forage. Non loin du carrefour Godomey.',
                'pieces' => 2,
                'chambres' => 1,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Godomey, non loin du carrefour',
                'ville' => 'Abomey-Calavi',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 32000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [5, 9],
            ],
            [
                'titre' => 'Maison à étage à vendre à Comè',
                'surface' => 135.00,
                'description' => 'Maison à étage 3 chambres salon à vendre à Comè, chef-lieu du Couffo. Cour clôturée, forage, quartier calme.',
                'pieces' => 4,
                'chambres' => 3,
                'salons' => 1,
                'etage' => 1,
                'adresse' => 'Comè centre',
                'ville' => 'Comè',
                'codePostal' => null,
                'categorie' => 'maison',
                'statut' => 'disponible',
                'prix' => 16000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [5, 9],
            ],
            [
                'titre' => 'Villa duplex à vendre à Grand-Popo',
                'surface' => 200.00,
                'description' => 'Villa duplex 4 chambres salon à vendre à Grand-Popo, à quelques minutes de la plage. Cour clôturée, jardin, forage, groupe électrogène.',
                'pieces' => 6,
                'chambres' => 4,
                'salons' => 1,
                'etage' => 1,
                'adresse' => 'Grand-Popo, bord de mer',
                'ville' => 'Grand-Popo',
                'codePostal' => null,
                'categorie' => 'villa',
                'statut' => 'disponible',
                'prix' => 55000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [3, 5, 8, 9],
            ],
            [
                'titre' => 'Studio meublé à louer à Akpakpa',
                'surface' => 23.00,
                'description' => 'Studio meublé et climatisé à louer à Akpakpa, non loin du port autonome de Cotonou. Sanitaire interne, forage.',
                'pieces' => 1,
                'chambres' => 0,
                'salons' => 0,
                'etage' => 0,
                'adresse' => 'Akpakpa, non loin du port',
                'ville' => 'Cotonou',
                'codePostal' => null,
                'categorie' => 'studio',
                'statut' => 'disponible',
                'prix' => 50000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [7, 9],
            ],
            [
                'titre' => '2 chambres salon à louer à Zogbadjè',
                'surface' => 52.00,
                'description' => '2 chambres salon à louer à Zogbadjè, Abomey-Calavi. Cour clôturée, forage, proche de l\'université.',
                'pieces' => 3,
                'chambres' => 2,
                'salons' => 1,
                'etage' => 0,
                'adresse' => 'Zogbadjè, Abomey-Calavi',
                'ville' => 'Abomey-Calavi',
                'codePostal' => null,
                'categorie' => 'appartement',
                'statut' => 'disponible',
                'prix' => 60000.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [5, 9],
            ],
            [
                'titre' => 'Villa basse à vendre à Kpomassè',
                'surface' => 145.00,
                'description' => 'Villa basse 3 chambres salon à vendre à Kpomassè, terrain clôturé de 450 m². Quartier calme non loin du centre.',
                'pieces' => 4,
                'chambres' => 3,
                'salons' => 1,
                'etage' => null,
                'adresse' => 'Kpomassè centre',
                'ville' => 'Kpomassè',
                'codePostal' => null,
                'categorie' => 'villa',
                'statut' => 'disponible',
                'prix' => 18000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [5, 9],
            ],
        ];

        // Le statut fusionne désormais la disponibilité et le type (vente/location)
        $statutCodes = [
            'disponible-vente'    => 'a_vendre',
            'disponible-location' => 'a_louer',
            'vendu-vente'         => 'vendu',
            'loue-location'       => 'loue',
            'reserve-vente'       => 'reserve',
            'reserve-location'    => 'reserve',
        ];

        foreach ($biens as $bienData) {
            $options = $bienData['options'];
            $typeBien = $bienData['type_bien'];
            $statutKey = $bienData['statut'] . '-' . $typeBien;
            unset($bienData['options'], $bienData['type_bien'], $bienData['statut']);

            $bienData['statut_id'] = Statut::where('code', $statutCodes[$statutKey])->value('id');

            $bien = Bien::create($bienData);

            // Attacher les options
            $bien->options()->sync($options);
        }
    }
}
