<?php

namespace Database\Seeders;
    
use App\Models\Bien;
use App\Models\Option;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class BienSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Récupérer tous les utilisateurs disponibles
        $users = User::all();
        
        // Si aucun utilisateur n'existe, créer un utilisateur par défaut
        if ($users->isEmpty()) {
            $users = collect([
                User::create([
                    'prenom' => 'Default',
                    'nom' => 'User',
                    'tel' => '0123456789',
                    'email' => 'default@immobilier.fr',
                    'password' => Hash::make('password'),
                    'type' => 'user',
                ])
            ]);
        }
        
        $biens = [
            [
                'titre' => 'Appartement T3 lumineux centre-ville',
                'surface' => 75.50,
                'description' => 'Bel appartement T3 de 75m² situé en plein centre-ville. Proche des commerces et transports. Très lumineux avec balcon.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 3,
                'adresse' => '15 Rue de la République',
                'ville' => 'Paris',
                'codePostal' => '75001',
                'statut' => 'disponible',
                'prix' => 450000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 3, 6], // Parking, Terrasse, Ascenseur
            ],
            [
                'titre' => 'Studio meublé prêt à louer',
                'surface' => 28.00,
                'description' => 'Studio de 28m² entièrement meublé, idéal pour étudiant ou jeune professionnel. Cuisine équipée, salle de bain moderne.',
                'pieces' => 1,
                'chambres' => 0,
                'etage' => 2,
                'adresse' => '8 Avenue des Champs-Élysées',
                'ville' => 'Paris',
                'codePostal' => '75008',
                'statut' => 'disponible',
                'prix' => 850.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [6, 8], // Ascenseur, Chauffage
            ],
            [
                'titre' => 'Maison familiale avec jardin',
                'surface' => 120.00,
                'description' => 'Spacieuse maison de 120m² avec jardin de 500m². 4 chambres, cuisine ouverte, double garage. Parfait pour une famille.',
                'pieces' => 6,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '25 Rue des Lilas',
                'ville' => 'Lyon',
                'codePostal' => '69000',
                'statut' => 'disponible',
                'prix' => 650000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5, 7], // Parking, Jardin, Cave, Climatisation
            ],
            [
                'titre' => 'Penthouse de luxe avec vue panoramique',
                'surface' => 180.00,
                'description' => 'Exceptionnel penthouse de 180m² au dernier étage. Vue imprenable sur la ville. Terrasse de 60m², piscine privée.',
                'pieces' => 5,
                'chambres' => 3,
                'etage' => 15,
                'adresse' => '100 Boulevard de la Mer',
                'ville' => 'Nice',
                'codePostal' => '06000',
                'statut' => 'disponible',
                'prix' => 2500000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 4, 6, 7, 9], // Toutes sauf cave
            ],
            [
                'titre' => 'Appartement T4 près du métro',
                'surface' => 95.00,
                'description' => 'Grand appartement T4 de 95m² très bien situé. 2 minutes à pied du métro. Idéal pour coloc ou famille.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => 5,
                'adresse' => '42 Rue Nationale',
                'ville' => 'Marseille',
                'codePostal' => '13001',
                'statut' => 'disponible',
                'prix' => 1200.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [6, 8, 10], // Ascenseur, Chauffage, Gardien
            ],
            [
                'titre' => 'Loft industriel rénové',
                'surface' => 150.00,
                'description' => 'Magnifique loft de 150m² dans ancienne usine rénovée. Hauteur sous plafond 4m, grandes baies vitrées, espace ouvert.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 1,
                'adresse' => '5 Quai de la Seine',
                'ville' => 'Bordeaux',
                'codePostal' => '33000',
                'statut' => 'reserve',
                'prix' => 780000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [3, 4, 7], // Terrasse, Jardin, Climatisation
            ],
            // Ajouts supplémentaires
            [
                'titre' => 'Appartement T2 dans quartier calme',
                'surface' => 45.00,
                'description' => 'T2 de 45m² en rez-de-chaussée avec petit jardin. Cuisine séparée, salle de bain rénovée. Idéal pour couple.',
                'pieces' => 2,
                'chambres' => 1,
                'etage' => 0,
                'adresse' => '12 Rue des Ecoles',
                'ville' => 'Toulouse',
                'codePostal' => '31000',
                'statut' => 'disponible',
                'prix' => 220000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [3, 5], // Terrasse, Cave
            ],
            [
                'titre' => 'Maison de village avec charme',
                'surface' => 85.00,
                'description' => 'Maison de village de 85m² avec cour intérieure. 3 chambres, dépendance. Travaux à prévoir.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => null,
                'adresse' => '3 Place du Marché',
                'ville' => 'Nantes',
                'codePostal' => '44000',
                'statut' => 'disponible',
                'prix' => 285000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 5], // Parking, Cave
            ],
            [
                'titre' => 'Chambre en colocation',
                'surface' => 18.00,
                'description' => 'Chambre de 18m² dans appartement en colocation. Salon partagé, cuisine équipée. Wifi inclus.',
                'pieces' => 1,
                'chambres' => 1,
                'etage' => 4,
                'adresse' => '67 Rue de la Victoire',
                'ville' => 'Lille',
                'codePostal' => '59000',
                'statut' => 'disponible',
                'prix' => 450.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [6, 8], // Ascenseur, Chauffage
            ],
            [
                'titre' => 'Villa moderne avec piscine',
                'surface' => 200.00,
                'description' => 'Villa contemporaine de 200m² avec piscine 8x4. 5 chambres, bureau, double garage. Secteur très recherché.',
                'pieces' => 7,
                'chambres' => 5,
                'etage' => null,
                'adresse' => '15 Avenue des Pins',
                'ville' => 'Cannes',
                'codePostal' => '06400',
                'statut' => 'disponible',
                'prix' => 1800000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 7], // Piscine, Parking, Jardin, Climatisation
            ],
            [
                'titre' => 'Appartement T1 hypercentre',
                'surface' => 22.00,
                'description' => 'Studio T1 de 22m² en plein centre. Idéal investissement locatif ou premier achat. Proche toutes commodités.',
                'pieces' => 1,
                'chambres' => 0,
                'etage' => 2,
                'adresse' => '33 Rue Gambetta',
                'ville' => 'Strasbourg',
                'codePostal' => '67000',
                'statut' => 'disponible',
                'prix' => 125000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6], // Ascenseur
            ],
            [
                'titre' => 'Maison de campagne rénovée',
                'surface' => 160.00,
                'description' => 'Belle maison de campagne de 160m² entièrement rénovée. 4 chambres, grand salon avec cheminée, terrain de 2000m².',
                'pieces' => 6,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '1 Chemin du Vieux Moulin',
                'ville' => 'Rennes',
                'codePostal' => '35000',
                'statut' => 'disponible',
                'prix' => 420000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5, 8], // Parking, Jardin, Cave, Chauffage
            ],
            [
                'titre' => 'Duplex avec terrasse',
                'surface' => 110.00,
                'description' => 'Duplex de 110m² avec grande terrasse de 40m². 3 chambres, cuisine américaine. Très lumineux.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => 4,
                'adresse' => '18 Boulevard Montmartre',
                'ville' => 'Paris',
                'codePostal' => '75009',
                'statut' => 'vendu',
                'prix' => 890000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [3, 4, 6, 7], // Terrasse, Jardin, Ascenseur, Climatisation
            ],
            [
                'titre' => 'Appartement T5 familial',
                'surface' => 130.00,
                'description' => 'Grand T5 de 130m² en quartier résidentiel. 4 chambres, 2 salles de bain, balcon. Parfait pour famille avec enfants.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => 3,
                'adresse' => '7 Avenue Foch',
                'ville' => 'Versailles',
                'codePostal' => '78000',
                'statut' => 'disponible',
                'prix' => 950000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 6, 8, 10], // Parking, Ascenseur, Chauffage, Gardien
            ],
            [
                'titre' => 'Studio étudiant meublé',
                'surface' => 20.00,
                'description' => 'Petit studio de 20m² meublé, proche université. Kitchenette, douche, WC. Loyer charges comprises.',
                'pieces' => 1,
                'chambres' => 0,
                'etage' => 1,
                'adresse' => '45 Rue de l\'Université',
                'ville' => 'Grenoble',
                'codePostal' => '38000',
                'statut' => 'loue',
                'prix' => 550.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [8], // Chauffage
            ],
            [
                'titre' => 'Maison architecte contemporaine',
                'surface' => 250.00,
                'description' => 'Maison d\'architecte de 250m² sur terrain plat. Baies vitrées, piscine, home cinéma. Construction haute qualité.',
                'pieces' => 8,
                'chambres' => 6,
                'etage' => null,
                'adresse' => '22 Route de la Corniche',
                'ville' => 'Biarritz',
                'codePostal' => '64200',
                'statut' => 'disponible',
                'prix' => 3200000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 4, 7, 9], // Piscine, Parking, Jardin, Terrasse, Climatisation, Interphone
            ],
            [
                'titre' => 'Appartement T3 rénové',
                'surface' => 68.00,
                'description' => 'T3 de 68m² entièrement rénové avec goût. Parquet flottant, cuisine neuve, double vitrage. Etage calme.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 6,
                'adresse' => '91 Rue Lecourbe',
                'ville' => 'Paris',
                'codePostal' => '75015',
                'statut' => 'disponible',
                'prix' => 520000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6, 8], // Ascenseur, Chauffage
            ],
            [
                'titre' => 'Maison de pêcheur',
                'surface' => 75.00,
                'description' => 'Charmante maison de pêcheur de 75m² à 500m de la plage. 3 chambres, jardin, abri de jardin. Ambiance authentique.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => null,
                'adresse' => '11 Rue du Port',
                'ville' => 'Saint-Malo',
                'codePostal' => '35400',
                'statut' => 'disponible',
                'prix' => 380000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5], // Parking, Jardin, Cave
            ],
            // 79 biens supplémentaires pour atteindre 100
            [
                'titre' => 'Appartement T4 vue mer',
                'surface' => 105.00,
                'description' => 'Magnifique T4 de 105m² avec vue panoramique sur la mer. 3 chambres, 2 salles de bain, terrasse de 25m².',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => 8,
                'adresse' => '55 Promenade des Anglais',
                'ville' => 'Nice',
                'codePostal' => '06000',
                'statut' => 'disponible',
                'prix' => 980000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [3, 4, 6, 7], // Terrasse, Jardin, Ascenseur, Climatisation
            ],
            [
                'titre' => 'Studio en centre-ville',
                'surface' => 25.00,
                'description' => 'Studio de 25m² en plein centre, proche de toutes les commodités. Idéal pour investissement locatif.',
                'pieces' => 1,
                'chambres' => 0,
                'etage' => 3,
                'adresse' => '12 Rue de la Paix',
                'ville' => 'Lyon',
                'codePostal' => '69000',
                'statut' => 'disponible',
                'prix' => 145000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6], // Ascenseur
            ],
            [
                'titre' => 'Maison avec terrain constructible',
                'surface' => 95.00,
                'description' => 'Maison de 95m² sur terrain de 800m² constructible. 4 chambres, possibilité d\'extension.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '22 Route de la Forêt',
                'ville' => 'Annecy',
                'codePostal' => '74000',
                'statut' => 'disponible',
                'prix' => 520000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5], // Parking, Jardin, Cave
            ],
            [
                'titre' => 'Appartement T2 rénové',
                'surface' => 42.00,
                'description' => 'T2 de 42m² entièrement rénové avec matériaux de qualité. Cuisine équipée, salle de bain moderne.',
                'pieces' => 2,
                'chambres' => 1,
                'etage' => 2,
                'adresse' => '8 Rue Victor Hugo',
                'ville' => 'Brest',
                'codePostal' => '29200',
                'statut' => 'disponible',
                'prix' => 185000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6, 8], // Ascenseur, Chauffage
            ],
            [
                'titre' => 'Villa avec vue lac',
                'surface' => 180.00,
                'description' => 'Superbe villa de 180m² avec vue sur le lac. 5 chambres, piscine, jardin arboré.',
                'pieces' => 6,
                'chambres' => 5,
                'etage' => null,
                'adresse' => '15 Chemin du Lac',
                'ville' => 'Annecy',
                'codePostal' => '74000',
                'statut' => 'disponible',
                'prix' => 1200000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 7], // Piscine, Parking, Jardin, Climatisation
            ],
            [
                'titre' => 'Appartement T3 quartier résidentiel',
                'surface' => 72.00,
                'description' => 'T3 de 72m² en quartier calme et résidentiel. Balcon, cave, parking.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 4,
                'adresse' => '34 Avenue des Lilas',
                'ville' => 'Clermont-Ferrand',
                'codePostal' => '63000',
                'statut' => 'disponible',
                'prix' => 265000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 5, 6], // Parking, Cave, Ascenseur
            ],
            [
                'titre' => 'Maison de caractère',
                'surface' => 140.00,
                'description' => 'Maison de caractère de 140m² avec éléments authentiques. 4 chambres, jardin, dépendance.',
                'pieces' => 6,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '5 Place du Château',
                'ville' => 'Dijon',
                'codePostal' => '21000',
                'statut' => 'disponible',
                'prix' => 480000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5, 8], // Parking, Jardin, Cave, Chauffage
            ],
            [
                'titre' => 'Appartement T1 meublé',
                'surface' => 28.00,
                'description' => 'Studio T1 meublé de 28m², prêt à vivre. Cuisine équipée, salle de bain, WC séparés.',
                'pieces' => 1,
                'chambres' => 0,
                'etage' => 5,
                'adresse' => '19 Rue de la République',
                'ville' => 'Metz',
                'codePostal' => '57000',
                'statut' => 'disponible',
                'prix' => 950.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [6, 8], // Ascenseur, Chauffage
            ],
            [
                'titre' => 'Maison contemporaine',
                'surface' => 165.00,
                'description' => 'Maison contemporaine de 165m² avec design moderne. 5 chambres, bureau, terrasse.',
                'pieces' => 7,
                'chambres' => 5,
                'etage' => null,
                'adresse' => '12 Allée des Chênes',
                'ville' => 'Tours',
                'codePostal' => '37000',
                'statut' => 'disponible',
                'prix' => 680000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 4, 7], // Parking, Jardin, Terrasse, Climatisation
            ],
            [
                'titre' => 'Appartement T4 spacieux',
                'surface' => 115.00,
                'description' => 'Grand T4 de 115m² très lumineux. 3 chambres, double séjour, balcon.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => 7,
                'adresse' => '45 Boulevard de la Liberté',
                'ville' => 'Rennes',
                'codePostal' => '35000',
                'statut' => 'disponible',
                'prix' => 420000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [4, 6, 8], // Terrasse, Ascenseur, Chauffage
            ],
            [
                'titre' => 'Fermette rénovée',
                'surface' => 180.00,
                'description' => 'Ancienne fermette entièrement rénovée de 180m². 4 chambres, grange aménageable, terrain 3000m².',
                'pieces' => 6,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '1 Route de la Ferme',
                'ville' => 'Limoges',
                'codePostal' => '87000',
                'statut' => 'disponible',
                'prix' => 380000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5, 8], // Parking, Jardin, Cave, Chauffage
            ],
            [
                'titre' => 'Appartement T2 centre commercial',
                'surface' => 48.00,
                'description' => 'T2 de 48m² proche centre commercial. 1 chambre, parking, cave.',
                'pieces' => 2,
                'chambres' => 1,
                'etage' => 1,
                'adresse' => '78 Rue du Commerce',
                'ville' => 'Le Havre',
                'codePostal' => '76600',
                'statut' => 'disponible',
                'prix' => 165000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 5], // Parking, Cave
            ],
            [
                'titre' => 'Maison avec piscine',
                'surface' => 135.00,
                'description' => 'Maison de 135m² avec piscine privée. 4 chambres, jardin, garage double.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '23 Avenue des Tilleuls',
                'ville' => 'Montpellier',
                'codePostal' => '34000',
                'statut' => 'disponible',
                'prix' => 750000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 7], // Piscine, Parking, Jardin, Climatisation
            ],
            [
                'titre' => 'Appartement T3 quartier historique',
                'surface' => 68.00,
                'description' => 'T3 de 68m² dans quartier historique. Charme ancien, haute qualité, proche transports.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 2,
                'adresse' => '15 Rue du Vieux Port',
                'ville' => 'Marseille',
                'codePostal' => '13002',
                'statut' => 'disponible',
                'prix' => 380000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6, 8, 10], // Ascenseur, Chauffage, Gardien
            ],
            [
                'titre' => 'Villa de prestige',
                'surface' => 280.00,
                'description' => 'Villa de prestige de 280m² avec tous les conforts. 6 chambres, piscine, tennis, parc de 5000m².',
                'pieces' => 8,
                'chambres' => 6,
                'etage' => null,
                'adresse' => '100 Route du Golfe',
                'ville' => 'Saint-Tropez',
                'codePostal' => '83990',
                'statut' => 'disponible',
                'prix' => 5500000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 4, 7, 9], // Piscine, Parking, Jardin, Terrasse, Climatisation, Interphone
            ],
            [
                'titre' => 'Appartement T5 en duplex',
                'surface' => 145.00,
                'description' => 'T5 duplex de 145m² avec terrasse sur deux niveaux. 4 chambres, 3 salles de bain.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => 5,
                'adresse' => '67 Rue de la Tour',
                'ville' => 'Lyon',
                'codePostal' => '69000',
                'statut' => 'disponible',
                'prix' => 890000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [3, 4, 6, 7], // Terrasse, Jardin, Ascenseur, Climatisation
            ],
            [
                'titre' => 'Maison de maître',
                'surface' => 220.00,
                'description' => 'Maison de maître de 220m² avec parc arboré. 5 chambres, bibliothèque, dépendances.',
                'pieces' => 7,
                'chambres' => 5,
                'etage' => null,
                'adresse' => '3 Avenue du Château',
                'ville' => 'Bordeaux',
                'codePostal' => '33000',
                'statut' => 'disponible',
                'prix' => 1800000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5, 8, 10], // Parking, Jardin, Cave, Chauffage, Gardien
            ],
            [
                'titre' => 'Appartement T2 rénové',
                'surface' => 38.00,
                'description' => 'T2 de 38m² rénové avec goût. Cuisine américaine, salle de bain moderne.',
                'pieces' => 2,
                'chambres' => 1,
                'etage' => 3,
                'adresse' => '29 Rue des Arts',
                'ville' => 'Lille',
                'codePostal' => '59000',
                'statut' => 'disponible',
                'prix' => 195000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6], // Ascenseur
            ],
            [
                'titre' => 'Maison avec vue montagne',
                'surface' => 155.00,
                'description' => 'Maison de 155m² avec vue imprenable sur les montagnes. 4 chambres, grand jardin.',
                'pieces' => 6,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '18 Chemin des Cimes',
                'ville' => 'Grenoble',
                'codePostal' => '38000',
                'statut' => 'disponible',
                'prix' => 620000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 7, 8], // Parking, Jardin, Climatisation, Chauffage
            ],
            [
                'titre' => 'Appartement T4 prestige',
                'surface' => 125.00,
                'description' => 'T4 prestige de 125m² dans immeuble de standing. 3 chambres, terrasse, services.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => 9,
                'adresse' => '101 Avenue des Champs-Élysées',
                'ville' => 'Paris',
                'codePostal' => '75008',
                'statut' => 'disponible',
                'prix' => 2100000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [3, 4, 6, 7, 9, 10], // Terrasse, Jardin, Ascenseur, Climatisation, Interphone, Gardien
            ],
            [
                'titre' => 'Maison provençale',
                'surface' => 170.00,
                'description' => 'Authentique maison provençale de 170m². 4 chambres, piscine, oliviers.',
                'pieces' => 6,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '45 Route des Oliviers',
                'ville' => 'Aix-en-Provence',
                'codePostal' => '13100',
                'statut' => 'disponible',
                'prix' => 980000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 7], // Piscine, Parking, Jardin, Climatisation
            ],
            [
                'titre' => 'Appartement T3 quartier calme',
                'surface' => 65.00,
                'description' => 'T3 de 65m² en quartier très calme. 2 chambres, balcon, cave.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 2,
                'adresse' => '12 Rue des Rosiers',
                'ville' => 'Nantes',
                'codePostal' => '44000',
                'statut' => 'disponible',
                'prix' => 320000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [3, 5, 6], // Terrasse, Cave, Ascenseur
            ],
            [
                'titre' => 'Maison moderne',
                'surface' => 145.00,
                'description' => 'Maison moderne de 145m² avec design épuré. 4 chambres, jardin, garage.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '7 Rue des Architectes',
                'ville' => 'Nancy',
                'codePostal' => '54000',
                'statut' => 'disponible',
                'prix' => 580000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 7, 8], // Parking, Jardin, Climatisation, Chauffage
            ],
            [
                'titre' => 'Appartement T2 meublé',
                'surface' => 35.00,
                'description' => 'T2 meublé de 35m², prêt à habiter. Cuisine équipée, salle de bain.',
                'pieces' => 2,
                'chambres' => 1,
                'etage' => 4,
                'adresse' => '56 Rue du Soleil',
                'ville' => 'Nice',
                'codePostal' => '06000',
                'statut' => 'disponible',
                'prix' => 1200.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [6, 8], // Ascenseur, Chauffage
            ],
            [
                'titre' => 'Maison avec grand terrain',
                'surface' => 125.00,
                'description' => 'Maison de 125m² sur terrain de 4000m². 4 chambres, potager, abri jardin.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '15 Route des Champs',
                'ville' => 'Angers',
                'codePostal' => '49000',
                'statut' => 'disponible',
                'prix' => 420000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5], // Parking, Jardin, Cave
            ],
            [
                'titre' => 'Appartement T4 familial',
                'surface' => 98.00,
                'description' => 'T4 familial de 98m², idéal pour famille. 3 chambres, double vitrage.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => 6,
                'adresse' => '34 Avenue des Familles',
                'ville' => 'Reims',
                'codePostal' => '51100',
                'statut' => 'disponible',
                'prix' => 340000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6, 8, 10], // Ascenseur, Chauffage, Gardien
            ],
            [
                'titre' => 'Maison d\'architecte',
                'surface' => 195.00,
                'description' => 'Maison d\'architecte de 195m² avec matériaux nobles. 5 chambres, vue dégagée.',
                'pieces' => 7,
                'chambres' => 5,
                'etage' => null,
                'adresse' => '9 Route du Belvédère',
                'ville' => 'La Rochelle',
                'codePostal' => '17000',
                'statut' => 'disponible',
                'prix' => 1200000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 4, 7], // Parking, Jardin, Terrasse, Climatisation
            ],
            [
                'titre' => 'Appartement T3 centre-ville',
                'surface' => 70.00,
                'description' => 'T3 de 70m² en plein centre-ville. 2 chambres, proche commerces et transports.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 3,
                'adresse' => '23 Rue Centrale',
                'ville' => 'Caen',
                'codePostal' => '14000',
                'statut' => 'disponible',
                'prix' => 285000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6], // Ascenseur
            ],
            [
                'titre' => 'Maison avec atelier',
                'surface' => 160.00,
                'description' => 'Maison de 160m² avec grand atelier. 4 chambres, garage, terrain.',
                'pieces' => 6,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '11 Route de l\'Atelier',
                'ville' => 'Le Mans',
                'codePostal' => '72000',
                'statut' => 'disponible',
                'prix' => 450000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5], // Parking, Jardin, Cave
            ],
            [
                'titre' => 'Appartement T2 lumineux',
                'surface' => 40.00,
                'description' => 'T2 très lumineux de 40m² avec balcon. Cuisine équipée, bonne exposition.',
                'pieces' => 2,
                'chambres' => 1,
                'etage' => 5,
                'adresse' => '67 Rue du Soleil Levant',
                'ville' => 'Brest',
                'codePostal' => '29200',
                'statut' => 'disponible',
                'prix' => 210000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [4, 6], // Terrasse, Ascenseur
            ],
            [
                'titre' => 'Maison de campagne',
                'surface' => 130.00,
                'description' => 'Maison de campagne de 130m² avec charme. 4 chambres, jardin fruitier.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '5 Chemin des Vignes',
                'ville' => 'Dijon',
                'codePostal' => '21000',
                'statut' => 'disponible',
                'prix' => 380000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5, 8], // Parking, Jardin, Cave, Chauffage
            ],
            [
                'titre' => 'Appartement T3 rénové',
                'surface' => 75.00,
                'description' => 'T3 de 75m² entièrement rénové. 2 chambres, cuisine moderne, salle de bain.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 4,
                'adresse' => '18 Rue Neuve',
                'ville' => 'Clermont-Ferrand',
                'codePostal' => '63000',
                'statut' => 'disponible',
                'prix' => 295000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6, 8], // Ascenseur, Chauffage
            ],
            [
                'titre' => 'Maison avec garage double',
                'surface' => 140.00,
                'description' => 'Maison de 140m² avec garage double. 4 chambres, jardin, terrasse.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '22 Avenue des Garages',
                'ville' => 'Tours',
                'codePostal' => '37000',
                'statut' => 'disponible',
                'prix' => 520000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 4], // Parking, Jardin, Terrasse
            ],
            [
                'titre' => 'Appartement T4 spacieux',
                'surface' => 110.00,
                'description' => 'Grand T4 de 110m² très spacieux. 3 chambres, double séjour, balcon.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => 7,
                'adresse' => '45 Boulevard Spacieux',
                'ville' => 'Lille',
                'codePostal' => '59000',
                'statut' => 'disponible',
                'prix' => 410000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [4, 6, 8], // Terrasse, Ascenseur, Chauffage
            ],
            [
                'titre' => 'Maison avec piscine',
                'surface' => 165.00,
                'description' => 'Maison de 165m² avec piscine chauffée. 5 chambres, jardin, garage.',
                'pieces' => 6,
                'chambres' => 5,
                'etage' => null,
                'adresse' => '18 Route de la Piscine',
                'ville' => 'Montpellier',
                'codePostal' => '34000',
                'statut' => 'disponible',
                'prix' => 890000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 7], // Piscine, Parking, Jardin, Climatisation
            ],
            [
                'titre' => 'Appartement T2 centre',
                'surface' => 45.00,
                'description' => 'T2 de 45m² en plein centre. 1 chambre, commerces à pied.',
                'pieces' => 2,
                'chambres' => 1,
                'etage' => 2,
                'adresse' => '33 Rue du Centre',
                'ville' => 'Metz',
                'codePostal' => '57000',
                'statut' => 'disponible',
                'prix' => 175000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6], // Ascenseur
            ],
            [
                'titre' => 'Maison avec grand jardin',
                'surface' => 150.00,
                'description' => 'Maison de 150m² avec grand jardin arboré. 4 chambres, terrasse, abri.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '7 Allée des Jardins',
                'ville' => 'Angers',
                'codePostal' => '49000',
                'statut' => 'disponible',
                'prix' => 480000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 4, 5], // Parking, Jardin, Terrasse, Cave
            ],
            [
                'titre' => 'Appartement T3 quartier calme',
                'surface' => 68.00,
                'description' => 'T3 de 68m² en quartier très calme. 2 chambres, balcon, parking.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 3,
                'adresse' => '12 Rue du Calme',
                'ville' => 'Reims',
                'codePostal' => '51100',
                'statut' => 'disponible',
                'prix' => 310000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 4, 6], // Parking, Terrasse, Ascenseur
            ],
            [
                'titre' => 'Maison moderne',
                'surface' => 135.00,
                'description' => 'Maison moderne de 135m² avec matériaux écologiques. 4 chambres, jardin.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '15 Rue Écologique',
                'ville' => 'Nancy',
                'codePostal' => '54000',
                'statut' => 'disponible',
                'prix' => 560000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 7, 8], // Parking, Jardin, Climatisation, Chauffage
            ],
            [
                'titre' => 'Appartement T4 vue ville',
                'surface' => 105.00,
                'description' => 'T4 de 105m² avec vue sur la ville. 3 chambres, terrasse, parking.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => 8,
                'adresse' => '88 Avenue de la Vue',
                'ville' => 'Lyon',
                'codePostal' => '69000',
                'statut' => 'disponible',
                'prix' => 520000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 4, 6, 7], // Parking, Terrasse, Ascenseur, Climatisation
            ],
            [
                'titre' => 'Maison avec terrain',
                'surface' => 120.00,
                'description' => 'Maison de 120m² sur terrain de 2000m². 4 chambres, puits, dépendance.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '3 Chemin du Puits',
                'ville' => 'Limoges',
                'codePostal' => '87000',
                'statut' => 'disponible',
                'prix' => 340000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5], // Parking, Jardin, Cave
            ],
            [
                'titre' => 'Appartement T2 meublé',
                'surface' => 38.00,
                'description' => 'T2 meublé de 38m², prêt à vivre. Cuisine équipée, salle de bain.',
                'pieces' => 2,
                'chambres' => 1,
                'etage' => 4,
                'adresse' => '45 Rue du Meublé',
                'ville' => 'Le Havre',
                'codePostal' => '76600',
                'statut' => 'disponible',
                'prix' => 850.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [6, 8], // Ascenseur, Chauffage
            ],
            [
                'titre' => 'Maison avec piscine',
                'surface' => 180.00,
                'description' => 'Maison de 180m² avec piscine et spa. 5 chambres, jardin, garage triple.',
                'pieces' => 6,
                'chambres' => 5,
                'etage' => null,
                'adresse' => '25 Route du Spa',
                'ville' => 'Bordeaux',
                'codePostal' => '33000',
                'statut' => 'disponible',
                'prix' => 1200000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 7], // Piscine, Parking, Jardin, Climatisation
            ],
            [
                'titre' => 'Appartement T3 rénové',
                'surface' => 72.00,
                'description' => 'T3 de 72m² entièrement rénové. 2 chambres, cuisine moderne, double vitrage.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 5,
                'adresse' => '67 Rue de la Rénovation',
                'ville' => 'Caen',
                'codePostal' => '14000',
                'statut' => 'disponible',
                'prix' => 330000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6, 8], // Ascenseur, Chauffage
            ],
            [
                'titre' => 'Maison de caractère',
                'surface' => 155.00,
                'description' => 'Maison de caractère de 155m² avec poutres apparentes. 4 chambres, cheminée.',
                'pieces' => 6,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '9 Route du Caractère',
                'ville' => 'Le Mans',
                'codePostal' => '72000',
                'statut' => 'disponible',
                'prix' => 490000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [3, 5, 8], // Jardin, Cave, Chauffage
            ],
            [
                'titre' => 'Appartement T4 prestige',
                'surface' => 118.00,
                'description' => 'T4 prestige de 118m² dans immeuble de standing. 3 chambres, services haut de gamme.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => 10,
                'adresse' => '200 Avenue du Standing',
                'ville' => 'Paris',
                'codePostal' => '75016',
                'statut' => 'disponible',
                'prix' => 1850000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [4, 6, 7, 9, 10], // Terrasse, Ascenseur, Climatisation, Interphone, Gardien
            ],
            [
                'titre' => 'Maison avec vue mer',
                'surface' => 145.00,
                'description' => 'Maison de 145m² avec vue sur mer. 4 chambres, terrasse, jardin.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '15 Route de la Mer',
                'ville' => 'La Rochelle',
                'codePostal' => '17000',
                'statut' => 'disponible',
                'prix' => 980000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 4, 7], // Parking, Jardin, Terrasse, Climatisation
            ],
            [
                'titre' => 'Appartement T2 centre-ville',
                'surface' => 42.00,
                'description' => 'T2 de 42m² en plein centre-ville. 1 chambre, commerces à proximité.',
                'pieces' => 2,
                'chambres' => 1,
                'etage' => 3,
                'adresse' => '78 Rue du Centre-Ville',
                'ville' => 'Brest',
                'codePostal' => '29200',
                'statut' => 'disponible',
                'prix' => 225000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6], // Ascenseur
            ],
            [
                'titre' => 'Maison avec grand garage',
                'surface' => 130.00,
                'description' => 'Maison de 130m² avec grand garage pour 4 voitures. 4 chambres, atelier.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '33 Avenue du Garage',
                'ville' => 'Tours',
                'codePostal' => '37000',
                'statut' => 'disponible',
                'prix' => 460000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5], // Parking, Jardin, Cave
            ],
            [
                'titre' => 'Appartement T3 lumineux',
                'surface' => 78.00,
                'description' => 'T3 très lumineux de 78m² avec double exposition. 2 chambres, balcon.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 4,
                'adresse' => '56 Rue de la Lumière',
                'ville' => 'Lille',
                'codePostal' => '59000',
                'statut' => 'disponible',
                'prix' => 380000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [4, 6, 8], // Terrasse, Ascenseur, Chauffage
            ],
            [
                'titre' => 'Maison avec potager',
                'surface' => 140.00,
                'description' => 'Maison de 140m² avec grand potager. 4 chambres, serre, puits.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '18 Route du Potager',
                'ville' => 'Angers',
                'codePostal' => '49000',
                'statut' => 'disponible',
                'prix' => 420000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5], // Parking, Jardin, Cave
            ],
            [
                'titre' => 'Appartement T4 familial',
                'surface' => 102.00,
                'description' => 'T4 familial de 102m², parfait pour famille. 3 chambres, double vitrage.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => 6,
                'adresse' => '89 Avenue Familiale',
                'ville' => 'Reims',
                'codePostal' => '51100',
                'statut' => 'disponible',
                'prix' => 360000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6, 8, 10], // Ascenseur, Chauffage, Gardien
            ],
            [
                'titre' => 'Maison d\'architecte',
                'surface' => 175.00,
                'description' => 'Maison d\'architecte de 175m² avec design unique. 5 chambres, vue panoramique.',
                'pieces' => 7,
                'chambres' => 5,
                'etage' => null,
                'adresse' => '12 Route de l\'Architecture',
                'ville' => 'Nancy',
                'codePostal' => '54000',
                'statut' => 'disponible',
                'prix' => 980000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 4, 7], // Parking, Jardin, Terrasse, Climatisation
            ],
            [
                'titre' => 'Appartement T2 meublé',
                'surface' => 36.00,
                'description' => 'T2 meublé de 36m², idéal jeune professionnel. Cuisine équipée, clim.',
                'pieces' => 2,
                'chambres' => 1,
                'etage' => 5,
                'adresse' => '23 Rue du Pro',
                'ville' => 'Nice',
                'codePostal' => '06000',
                'statut' => 'disponible',
                'prix' => 1100.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [6, 7], // Ascenseur, Climatisation
            ],
            [
                'titre' => 'Maison avec étang',
                'surface' => 160.00,
                'description' => 'Maison de 160m² avec étang privé. 4 chambres, jardin, ponton.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '7 Route de l\'Étang',
                'ville' => 'Limoges',
                'codePostal' => '87000',
                'statut' => 'disponible',
                'prix' => 520000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5], // Parking, Jardin, Cave
            ],
            [
                'titre' => 'Appartement T3 rénové',
                'surface' => 69.00,
                'description' => 'T3 de 69m² rénové avec goût. 2 chambres, cuisine moderne, balcon.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 4,
                'adresse' => '34 Rue de la Rénovation',
                'ville' => 'Caen',
                'codePostal' => '14000',
                'statut' => 'disponible',
                'prix' => 315000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [4, 6], // Terrasse, Ascenseur
            ],
            [
                'titre' => 'Maison avec verrière',
                'surface' => 145.00,
                'description' => 'Maison de 145m² avec magnifique verrière. 4 chambres, jardin, véranda.',
                'pieces' => 6,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '16 Route de la Verrière',
                'ville' => 'Le Mans',
                'codePostal' => '72000',
                'statut' => 'disponible',
                'prix' => 580000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [3, 4, 7, 8], // Jardin, Terrasse, Climatisation, Chauffage
            ],
            [
                'titre' => 'Appartement T4 vue parc',
                'surface' => 108.00,
                'description' => 'T4 de 108m² avec vue sur parc. 3 chambres, terrasse, parking.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => 7,
                'adresse' => '91 Avenue du Parc',
                'ville' => 'Lyon',
                'codePostal' => '69000',
                'statut' => 'disponible',
                'prix' => 480000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 4, 6, 7], // Parking, Terrasse, Ascenseur, Climatisation
            ],
            [
                'titre' => 'Maison avec tennis',
                'surface' => 190.00,
                'description' => 'Maison de 190m² avec court de tennis. 5 chambres, piscine, grand parc.',
                'pieces' => 7,
                'chambres' => 5,
                'etage' => null,
                'adresse' => '28 Route du Tennis',
                'ville' => 'Bordeaux',
                'codePostal' => '33000',
                'statut' => 'disponible',
                'prix' => 1500000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 7], // Piscine, Parking, Jardin, Climatisation
            ],
            [
                'titre' => 'Appartement T2 centre',
                'surface' => 44.00,
                'description' => 'T2 de 44m² en plein centre. 1 chambre, transports à porte.',
                'pieces' => 2,
                'chambres' => 1,
                'etage' => 2,
                'adresse' => '56 Rue du Centre',
                'ville' => 'Metz',
                'codePostal' => '57000',
                'statut' => 'disponible',
                'prix' => 195000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [6], // Ascenseur
            ],
            [
                'titre' => 'Maison avec bois',
                'surface' => 155.00,
                'description' => 'Maison de 155m² avec bois de 2 hectares. 4 chambres, étang, nature.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '1 Route du Bois',
                'ville' => 'Angers',
                'codePostal' => '49000',
                'statut' => 'disponible',
                'prix' => 650000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5], // Parking, Jardin, Cave
            ],
            [
                'titre' => 'Appartement T3 calme',
                'surface' => 71.00,
                'description' => 'T3 très calme de 71m². 2 chambres, balcon, cave, parking.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 3,
                'adresse' => '23 Rue du Calme',
                'ville' => 'Reims',
                'codePostal' => '51100',
                'statut' => 'disponible',
                'prix' => 325000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 4, 5, 6], // Parking, Terrasse, Cave, Ascenseur
            ],
            [
                'titre' => 'Maison contemporaine',
                'surface' => 140.00,
                'description' => 'Maison contemporaine de 140m² avec design épuré. 4 chambres, jardin moderne.',
                'pieces' => 5,
                'chambres' => 4,
                'etage' => null,
                'adresse' => '14 Rue Contemporaine',
                'ville' => 'Nancy',
                'codePostal' => '54000',
                'statut' => 'disponible',
                'prix' => 620000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 7, 8], // Parking, Jardin, Climatisation, Chauffage
            ],
            [
                'titre' => 'Appartement T4 duplex',
                'surface' => 125.00,
                'description' => 'T4 duplex de 125m² avec terrasses sur 2 niveaux. 3 chambres, beaucoup de lumière.',
                'pieces' => 4,
                'chambres' => 3,
                'etage' => 6,
                'adresse' => '78 Avenue du Duplex',
                'ville' => 'Lyon',
                'codePostal' => '69000',
                'statut' => 'disponible',
                'prix' => 680000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [4, 6, 7], // Terrasse, Ascenseur, Climatisation
            ],
            [
                'titre' => 'Maison avec orangeraie',
                'surface' => 165.00,
                'description' => 'Maison de 165m² avec orangeraie. 5 chambres, jardin méditerranéen, fontaine.',
                'pieces' => 6,
                'chambres' => 5,
                'etage' => null,
                'adresse' => '35 Route de l\'Orangerie',
                'ville' => 'Montpellier',
                'codePostal' => '34000',
                'statut' => 'disponible',
                'prix' => 950000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 7], // Piscine, Parking, Jardin, Climatisation
            ],
            [
                'titre' => 'Appartement T2 meublé',
                'surface' => 39.00,
                'description' => 'T2 meublé de 39m², prêt à vivre. Cuisine équipée, salle de bain, clim.',
                'pieces' => 2,
                'chambres' => 1,
                'etage' => 4,
                'adresse' => '67 Rue du Meublé',
                'ville' => 'Le Havre',
                'codePostal' => '76600',
                'statut' => 'disponible',
                'prix' => 900.00,
                'type_bien' => 'location',
                'user_id' => $users->random()->id,
                'options' => [6, 7], // Ascenseur, Climatisation
            ],
            [
                'titre' => 'Maison avec rivière',
                'surface' => 175.00,
                'description' => 'Maison de 175m² avec rivière bordant le terrain. 5 chambres, ponton, nature.',
                'pieces' => 6,
                'chambres' => 5,
                'etage' => null,
                'adresse' => '8 Route de la Rivière',
                'ville' => 'Limoges',
                'codePostal' => '87000',
                'statut' => 'disponible',
                'prix' => 680000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [2, 3, 5], // Parking, Jardin, Cave
            ],
            [
                'titre' => 'Appartement T3 haut standing',
                'surface' => 85.00,
                'description' => 'T3 haut standing de 85m² avec prestations luxe. 2 chambres, services concierge.',
                'pieces' => 3,
                'chambres' => 2,
                'etage' => 9,
                'adresse' => '150 Avenue du Standing',
                'ville' => 'Paris',
                'codePostal' => '75007',
                'statut' => 'disponible',
                'prix' => 1200000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [4, 6, 7, 9, 10], // Terrasse, Ascenseur, Climatisation, Interphone, Gardien
            ],
            [
                'titre' => 'Maison avec heliport',
                'surface' => 220.00,
                'description' => 'Maison de luxe de 220m² avec heliport privé. 6 chambres, domaine de 10 hectares.',
                'pieces' => 8,
                'chambres' => 6,
                'etage' => null,
                'adresse' => '1 Route de l\'Hélicoptère',
                'ville' => 'Saint-Tropez',
                'codePostal' => '83990',
                'statut' => 'disponible',
                'prix' => 8000000.00,
                'type_bien' => 'vente',
                'user_id' => $users->random()->id,
                'options' => [1, 2, 3, 4, 7, 9], // Piscine, Parking, Jardin, Terrasse, Climatisation, Interphone
            ],
        ];

        foreach ($biens as $bienData) {
            $options = $bienData['options'];
            $typeBien = $bienData['type_bien'];
            unset($bienData['options'], $bienData['type_bien']);

            $bien = Bien::create($bienData);

            // Attacher les options
            $bien->options()->sync($options);
        }
    }
}
